---@class utils
---@field get_language fun(): string
---@field get_server_time fun(callback_millis: function)
---@field send_platform_message fun(message: string)
---@field get_platform_id fun(): string
